Add events.
juancampa/membrane-driver-github pull request #1
Opened 2018-08-10 16:51 UTC by aranajhonny

* `issueOpened`
* `pullRequestOpened`
* `PullRequestCollection`
* `PullRequestPage`
* `PullRequest`

2018-08-10 17:16 UTC, juancampa requested changes

2018-08-10 17:16 UTC, juancampa commented on config.json
> +            "name": "pullRequest",
pluralize?

2018-08-10 17:16 UTC, juancampa commented on config.json
> +              }
These two should be refs

2018-08-10 17:16 UTC, juancampa commented on config.json
> +            "type": "String"
Shouldn't the type here be "Hook"?

2018-08-10 17:16 UTC, juancampa commented on config.json
> +        "name": "Events",
Empty type

2018-08-10 17:16 UTC, juancampa commented on index.js
> +  pullRequest({ self, source }) { return {}; },
feel free to remove unused params

2018-08-10 17:16 UTC, juancampa commented on index.js
> +  await program.setTimer(`${owner}/${repo}`, timer);
minor: can use `key` here.

2018-08-10 17:16 UTC, juancampa commented on index.js
> +    return self || parent.ref.pop().pop().push('one', { id: source.hook_id });
`self` resolvers should now be written in this form:

`return parent.parent.parent.one({ id: source.hook_id })`

For clarity, here's what it means:

 - `parent` is a ref to the `[Hook]` inside a page
 - `parent.parent` is a ref to the the `HookPage` in the collection
 - `parent.parent.parent` is a ref to the `HookCollection`
 - And from the ref to the collection we just go into the `one` field with the right id

2018-08-13 23:50 UTC, aranajhonny commented
@juancampa  check https://github.com/aranajhonny/subscribe-to-pr

2018-08-14 16:05 UTC, juancampa requested changes

2018-08-14 16:05 UTC, juancampa commented on index.js
> +      await program.setTimer(`${owner}/${repo}`, 0, 10);
This should trigger the timer immediately instead of 10s in the future. Call `timer(`${owner}/${repo}`)` directly?

2018-08-14 16:13 UTC, merged

2023-01-19 16:38 UTC, aranajhonny commented
prueba